name: Ephemeral-Benchnet2-Setup

on:
  pull_request:
    branches:
      - master
      - 'auto-cadence-upgrade/**'
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'

env:
  GO_VERSION: 1.19

jobs:
  create-kubernetes-env:
    name: Create Kubernetes Containers
    runs-on: ubuntu-latest
    steps:
      - name: Create containers
        # uses: helm command

  build-flow-images:
    name: Build Flow Docker Images
    runs-on: ubuntu-latest
    outputs:
      image-container-registry: registry name
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Docker Compose
        # uses: docker compose
      
  deploy-docker-images:
    name: Deploy Branch Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy containers
        # uses: kubernetes command

  setup-testroot-account:
    name: Setup E2E Testroot Account
    runs-on: ubuntu-latest
    steps:
      - name: setup account
        # uses: flow CLI command
      - name: add flow tokens
        # uses: flow CLI command

  destroy-env:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - name: stop network
       # uses: kubernetes command
      - name: turn off machines
       # uses: helm