name: Build Node Docker Images
# This workflow is used to build and push one-off images for specific node types. This is useful
# when deploying hotfixes or any time a change is not needed for all node roles.

on:
  workflow_dispatch:
    inputs:

jobs:
  docker-push:
    name: images
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Checkout repo
      uses: actions/checkout@v2

    # Provide Google Service Account credentials to Github Action, allowing interaction with the Google Container Registry
    # Logging in as github-actions@dl-flow.iam.gserviceaccount.com
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCR_SERVICE_KEY_SECRET }}
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Authenticate docker with gcloud
      run: |
        gcloud auth configure-docker

    - name: Build/Push
      env:
        IMAGE_TAG: haswell_test
      run: |
        make docker-build docker-push 
          


        
