name: CI

on:
  push:
    branches:
      - 'auto-cadence-upgrade/**'
      - staging
      - trying
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master*
      - 'auto-cadence-upgrade/**'
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  merge_group:
    branches:
      - master

env:
  GO_VERSION: "1.20"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        dir: [./, ./integration/, ./crypto/, ./insecure/]
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Install C formatter
      run: sudo apt-get install -y clang-format
    - name: Run C formatter and sanitizer for ./crypto
      run: make -C crypto c-format && make -C crypto c-sanitize
    - name: Run go generate
      run: go generate
      working-directory: ${{ matrix.dir }}
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.54
        args: -v
        working-directory: ${{ matrix.dir }}
        # https://github.com/golangci/golangci-lint-action/issues/244
        skip-cache: true

  create-dynamic-test-matrix:
    name: Create Dynamic Test Matrix
    runs-on: ubuntu-latest
    outputs:
      dynamic-matrix: ${{ steps.set-test-matrix.outputs.dynamicMatrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Set Test Matrix
        id: set-test-matrix
        run: go run utils/test_matrix/test_matrix.go admin cmd consensus engine/access engine/collection engine/common engine/consensus engine/execution/ingestion:buildjet-8vcpu-ubuntu-2204 engine/execution/computation engine/execution engine/verification engine:buildjet-4vcpu-ubuntu-2204 fvm ledger module/dkg module:buildjet-4vcpu-ubuntu-2204 network/alsp network/test/cohort1:buildjet-16vcpu-ubuntu-2204 network/test/cohort2:buildjet-4vcpu-ubuntu-2204 network/p2p/connection network/p2p/p2pnode:buildjet-4vcpu-ubuntu-2204 network/p2p/scoring network/p2p network state storage utils

  docker-build:
    name: Docker Build
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # all tags are needed for integration tests
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Docker build
        run: make docker-build-flow docker-build-flow-corrupt
      - name: Save Docker images
        run: |
          docker save \
          gcr.io/flow-container-registry/access:latest \
          gcr.io/flow-container-registry/collection:latest \
          gcr.io/flow-container-registry/consensus:latest \
          gcr.io/flow-container-registry/execution:latest \
          gcr.io/flow-container-registry/ghost:latest \
          gcr.io/flow-container-registry/observer:latest \
          gcr.io/flow-container-registry/verification:latest \
          gcr.io/flow-container-registry/access-corrupted:latest \
          gcr.io/flow-container-registry/execution-corrupted:latest \
          gcr.io/flow-container-registry/verification-corrupted:latest > flow-docker-images.tar
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: flow-docker-images.tar
          # use the workflow run id as part of the cache key to ensure these docker images will only be used for a single workflow run
          key: flow-docker-images-${{ hashFiles('**/Dockerfile') }}-${{ github.run_id }}

  integration-test:
    name: Integration Tests
    needs: docker-build
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Access Cohort1 Integration Tests
            make: make -C integration access-cohort1-tests
            runner: buildjet-4vcpu-ubuntu-2204
          - name: Access Cohort2 Integration Tests
            make: make -C integration access-cohort2-tests
            runner: ubuntu-latest
          - name: Access Cohort3 Integration Tests
            make: make -C integration access-cohort3-tests
            runner: ubuntu-latest
   runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          # all tags are needed for integration tests
          fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Load cached Docker images
      uses: actions/cache@v3
      with:
        path: flow-docker-images.tar
        # use the same cache key as the docker-build job
        key: flow-docker-images-${{ hashFiles('**/Dockerfile') }}-${{ github.run_id }}
    - name: Load Docker images
      run: docker load -i flow-docker-images.tar
    - name: Run tests (${{ matrix.name }})
      # TODO(rbtz): re-enable when we fix exisiting races.
      #env:
      #  RACE_DETECTOR: 1
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 35
        max_attempts: 1
        command: VERBOSE=1 ${{ matrix.make }}
